--- # Verify blessed CIDR access over privatelink connectivity
# Play 1: Test AAP Platform access via PrivateLink
# Test Scenario: Verify AAP Platform access via PrivateLink using a curl request
# Expected Result: HTTP 200 status and PrivateLink IP (10.x.x.x) usage

- name: Test AAP Platform access via PrivateLink
  hosts: all
  gather_facts: false

  vars:
    platform_url: "https://platform.cus-jemarmolm.aws.ansiblecloud.com"  # FIXME: default after preprod  is live

  tasks:
    - name: Run curl and show command/output
      shell: |
        echo "Running: curl -vk {{ platform_url }}"
        curl -vk -o /dev/null --silent --show-error {{ platform_url }} 2>&1
      register: result
      changed_when: false

    - name: Assert HTTP 200 status in response
      assert:
        that:
          - "'HTTP/1.1 200' in result.stdout"

    - name: Assert PrivateLink connection is used (10.x.x.x)
      assert:
        that:
          - "'Trying 10.' in result.stdout"

# Play 2: Test access to Mesh WebSocket endpoints via PrivateLink
# Test Scenario: Verify Mesh WebSocket access via PrivateLink to mesh-ingress-0 and mesh-ingress-1
# Expected Result: Successful WebSocket connection to mesh-ingress-0 and mesh-ingress-1 endpoints

- name: Test access to Mesh WebSocket endpoints via privatelink
  hosts: all
  gather_facts: true  # to get 'ansible_hostname' info

  vars:
    mesh_ingress_0_url: "wss://mesh-ingress-0.cus-jemarmolm.aws.ansiblecloud.com"
    mesh_ingress_1_url: "wss://mesh-ingress-1.cus-jemarmolm.aws.ansiblecloud.com"
    cert_path: "/etc/receptor/tls/{{ ansible_hostname }}.ec2.internal.crt"
    key_path: "/etc/receptor/tls/{{ ansible_hostname }}.ec2.internal.key"
    ca_path: "/etc/receptor/tls/automation-controller-root-ca.crt"
    json_payload: "{\"action\": \"helloWorld\"}"

    # test command
    wscat_command: >
      sudo $(which wscat)
      -c {{ item }}
      --cert {{ cert_path }}
      --key {{ key_path }}
      --ca {{ ca_path }}
      --no-check
      -w 1
      -x '{{ json_payload }}'

  tasks:
    - name: pre-checks
      block:
        - name: Set default localhost entries in /etc/hosts
          copy:
            dest: /etc/hosts
            content: |
              127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
              ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
            owner: root
            group: root
            mode: '0644'
          become: true

    - name: Check if Node.js is installed
      command: node -v
      register: node_check
      ignore_errors: true

    - name: Install Node.js if not installed
      dnf:
        name: nodejs
        state: present
      when: node_check.failed

    - name: Install wscat using npm locally if not installed
      command: npm install --prefix /home/{{ ansible_user }}/.local wscat
      when: node_check.rc == 0

    - name: Test connection to mesh-ingress-0
      shell: |
        echo "Running: {{ wscat_command }}"
        {{ wscat_command }}
      register: result_mesh_0
      changed_when: false
      failed_when: false
      loop:
        - "{{ mesh_ingress_0_url }}"

    - name: Assert successful connection to mesh-ingress-0
      assert:
        that:
          - "'NodeID' in result_mesh_0.results[0].stdout"
          - "'mesh-ingress-0' in result_mesh_0.results[0].stdout"

    - name: Test connection to mesh-ingress-1
      shell: |
        echo "Running: {{ wscat_command }}"
        {{ wscat_command }}
      register: result_mesh_1
      changed_when: false
      failed_when: false
      loop:
        - "{{ mesh_ingress_1_url }}"

    - name: Assert successful connection to mesh-ingress-1
      assert:
        that:
          - "'NodeID' in result_mesh_1.results[0].stdout"
          - "'mesh-ingress-1' in result_mesh_1.results[0].stdout"
...