---
- name: Test AAP Platform access via PrivateLink
  hosts: all
  gather_facts: false

  vars:
    platform_url: "https://platform.cus-jemarmolm.aws.ansiblecloud.com"  # FIXME: default after preprod  is live

  tasks:
    - name: Run curl and show command/output
      shell: |
        echo "Running: curl -vk {{ platform_url }}"
        curl -vk -o /dev/null --silent --show-error {{ platform_url }} 2>&1
      register: result
      changed_when: false

    - name: Assert HTTP 200 status in response
      assert:
        that:
          - "'HTTP/1.1 200' in result.stdout"

    - name: Assert PrivateLink connection is used (10.x.x.x)
      assert:
        that:
          - "'Trying 10.' in result.stdout"
...
