---
- name: Test access via PrivateLink
  hosts: all
  gather_facts: false

  vars:
    platform_url: "https://platform.cus-jemarmolm.aws.ansiblecloud.com"

  tasks:
    - name: Run curl to AAP platform URL and print command
      shell: |
        echo "curl -vk -o /dev/null --silent --show-error {{ platform_url }} 2>&1 | tee /tmp/curl_output.log"
        curl -vk -o /dev/null --silent --show-error {{ platform_url }} 2>&1 | tee /tmp/curl_output.log
      register: curl_output
      changed_when: false

    - name: Show curl output
      debug:
        var: curl_output.stdout

    - name: Fail if HTTP 200 not returned
      fail:
        msg: "Expected HTTP 200.\nOutput:\n{{ curl_output.stdout }}"
      when: "'HTTP/1.1 200' not in curl_output.stdout"

    - name: Fail if connection did not use PrivateLink (10.x.x.x)
      fail:
        msg: "Expected PrivateLink connection (10.x.x.x).\nOutput:\n{{ curl_output.stdout }}"
      when: "curl_output.stdout is not search('Trying 10\\.')"
...
